### ISSUE TITLE
ISOBMFF in a WinRT Component for UWP!

### ISSUE THREAD

**Issue by moutasem1989** [DigiDNA/ISOBMFF#11]
This is less of an issue and more of a call for help!
I am trying to port [ISOBMFF](https://github.com/DigiDNA/ISOBMFF) into a **Windows Runtime Component** using this [guid](https://docs.microsoft.com/en-us/cpp/porting/how-to-use-existing-cpp-code-in-a-universal-windows-platform-app?view=vs-2019) in order to call the API from my C# UWP aplication. In my application i am trying to get **Image collection** and thier thumbnails in **HEIC containers** [( Example ! )](https://drive.google.com/file/d/1JZc9tRfISDjBCjg3VAQXdH7BqHBqLWTW/view?usp=sharing)  . On the other hand I am also trying to write several Images as a collection into a HEIC container. 
I am hardly familiar with C++ which is the biggest obstacle I am facing.
It would be a great help it this library was accessable from other code languages (perhaps even as a **NUGET**

**Comment by macmade** [comment]
Unfortunately I'm not familiar with UWP.

As I understand, you should first try to compile the project with `/ZW`.  
Should be straightforward with the existing VisualStudio projects.

Then if you have issues, feel free to comment.

Also, in order to use ISOBMFF with other languages, like C#, I recommend you check SWIG: http://www.swig.org  
It can generate wrappers on top on C++ code.
