### ISSUE TITLE
Any chance we can write to the MP4

### ISSUE THREAD

**Issue by nonlin** [DigiDNA/ISOBMFF#21]
Write custom boxes and other custom metadata for parsing later?

**Comment by macmade** [comment]
I’m not sure I understand what you need.  
Can you add a little more details?

**Comment by rajhlinux** [comment]
What you want to do is to write/add/modify the MP4 atom box. 

Best way to do this is to use bento4's tools such as mp4edit.
Or using AtomicPasrley.
However these are not good to modify the values for some atoms, such as the values for the stco/co64 atom values of "chunk_offset".

The best way now is to still using a hex editor, create/modify the atom box into sections using a hex editor, then use bento4 mp4edit to take the atom box and insert/replace into the mp4 file.
 
You can first use bento4 mp4extract to extract an atom box and then modify it using a hex editor. Then use bento4 mp4edit to replace it back into the mp4 file.

Note, that changing values in the atom must also change all other atoms size above it.
This is why you need to use bento4 tools to do the replacement or insert. It usually automatically adjust the values of the atom hierarchy boxes. Since the mp4 specification requires that all atom boxes size must be predefined in the mp4 file. 

I read that this github (java based) can do what we want:
https://github.com/sannies/mp4parser

**Comment by macmade** [comment]
There is currently no plan to add support for writing back information to MPEG-4 files.

If you need this, using another tool such as the ones mentionned by @rajhlinux are probably your best option.
